const express = require('express')
const cors = require('cors')
const userRouter = require('./routes/user')
const movieRouter = require('./routes/movies')
const reviewRouter = require('./routes/review')
const authorization = require('./routes/authorization')
const app = express()
app.use(cors())
app.use(express.json())
//app.use(authorization)
app.use('/user', userRouter)
app.use('/movies', movieRouter)
app.use('/review', reviewRouter)
app.listen(4000, 'localhost', () => {
    console.log("Server started at port 4000")
})